//Contains the Number of the versions of all dependencies in the gradle
object Versions{

    const val androidVersion="8.1.0"
    const val appCompat= "1.6.1"
    const val assertJVersion="3.24.2"
    const val axTestCore="1.5.0"
    const val compileAndTargetSdk=34
    const val constraintLayout= "2.1.4"
    const val coreKtx="1.12.0"
    const val coreTesting= "2.2.0"
    const val coroutines="1.7.1"
    const val daggerHilt="2.46"
    const val espresso="3.5.1"
    const val glideVersion="4.15.1"
    const val gradleNavigationArgVersion= "2.7.3"
    const val gradleVersion="2.3.0"
    const val hiltCompiler="1.0.0"
    const val javaxInjectVersion = "1"
    const val junit= "4.13.2"
    const val junitExt="1.1.5"
    const val junitUi="4"
    const val jvmTarget="17"
    const val ktLintVersion="11.3.1"
    const val kotlinCompilerExtensionVersion="1.4.3"
    const val kotlinVersion="1.9.0"
    const val ktxActivity="1.7.2"
    const val lifeCycleExtensions="2.2.0"
    const val lifeCycleViewModel="2.6.2"
    const val lottieVersion= "6.0.0"
    const val materialDesign="1.9.0"
    const val minSdk=26
    const val mockitoCore= "3.11.0"
    const val mockitoInlineVersion="3.10.0"
    const val mockitoKotlinVersion="2.2.0"
    const val moshiConverterVersion= "2.9.0"
    const val navigation="2.5.2"
    const val okHttp="4.9.0"
    const val okHttpLogger="4.8.0"
    const val pagination= "3.2.1"
    const val picasso= "2.5.2"
    const val retrofit="2.9.0"
    const val robolectricVersion= "4.2.1"
    const val room="2.5.2"
    const val swipeRefreshLayout="1.1.0"
    const val versionName="1.0"
    const val versionCode=1

}